openapi: 3.0.3
info:
  title: WASAText API
  description: API for WASAText.
  version: 1.0.0

tags:
  - name: login
    description: Operations related to user authentication
  - name: user
    description: User related operations
  - name: conversations
    description: Operations related to conversations
  - name: messages
    description: Messages functionalities
  - name: reactions
    description: Reactions to messages
  - name: groups
    description: Group chat operations and management

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        Allows a user to log in by providing a username.
        If the username does not exist, it will be created.
      operationId: doLogin
      requestBody:
        description: Details required for user login
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Username to login
              properties:
                name:
                  type: string
                  description: The username to log in
                  example: Maria
                  pattern: '^[a-zA-Z]+$'
                  minLength: 3
                  maxLength: 16
              required:
                - name
      responses:
        '201':
          description: User logged in successfully 
          content:
            application/json:
              schema:
                type: object
                description: Identifier of the logged-in user
                properties:
                  identifier:
                    type: string
                    description: A unique identifier for the logged-in user
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 16
                    example: "abcdef012345"

  /users/{username}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
          description: The username of the user
          pattern: '^[a-zA-Z]+$'
          minLength: 3
          maxLength: 16
          
          
    put:
      tags:
        - user
      summary: Updates the username
      description: Allows the user to update their username
      operationId: setMyUserName
      requestBody:
        description: The new username to update
        required: true
        content:
          application/json:
            schema:
              type: object
              description: New username
              properties:
                new_name:
                  type: string
                  description: New username
                  example: "NewName"
                  pattern: '^[a-zA-Z]+$'
                  minLength: 3
                  maxLength: 16
              required:
                - new_name
      responses:
        '200':
          description: Username updated successfully
          content:
            application/json:
              schema:
                type: object
                description: Message of confirmation with the updated username
                properties:
                  message:
                    type: string
                    description: Confirmation message
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 30
                    example: "Username succesfully updated"
                  username:
                    type: string
                    description: The updated username
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 16
                    example: "NewName"

  /users/{username}/conversations:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
          pattern: '^[a-zA-Z]+$'
          minLength: 3
          maxLength: 16
          description: The username of the user
    get:
      tags:
        - conversations
      summary: List of a users conversations
      description: Returns a list of all conversations for a user
      operationId: getMyConversations
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                description: Conversations
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  properties:
                    conversation_id:
                      type: string
                      description: Unique identifier for the conversation
                    last_message:
                      type: string
                      description: Preview of the last message
                    timestamp:
                      type: string
                      format: date-time
                      description: Timestamp of the last message
                    participants:
                      type: array
                      description: List of participants in the conversation
                      items:
                        type: string
                      minItems: 1
                      maxItems: 50

  /conversations/{conversation_id}:
    parameters:
      - name: conversation_id
        in: path
        required: true
        schema:
          type: string
          description: The unique identifier for the conversation
          pattern: '^[a-zA-Z]+$'
          minLength: 3
          maxLength: 16
          
    get:
      tags:
        - conversations
      summary: Details of a specific conversation
      description: Returns all details of a specific conversation
      operationId: getConversation
      responses:
        '200':
          description: Details of the conversation
          content:
            application/json:
              schema:
                type: object
                description: Conversation details
                properties:
                  messages:
                    type: array
                    minItems: 1
                    maxItems: 200
                    description: List of messages in the conversation
                    items:
                      type: object
                      properties:
                        message_id:
                          type: string
                          description: Unique identifier for the message
                        sender:
                          type: string
                          description: Username of the sender
                        content:
                          type: string
                          description: The message content
                        timestamp:
                          type: string
                          format: date-time
                          description: Timestamp of the message

  /conversations/{conversation_id}/messages:
    parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            description: Unique identifier for the conversation
            pattern: '^[a-zA-Z]+$'
            minLength: 3
            maxLength: 16
             
    post:
      tags:
        - messages
      summary: Send a new message to the conversation
      description: Allows a user to send a new message to a conversation
      operationId: sendMessage
      requestBody:
        description: Message content
        required: true
        content:
          application/json:
            schema:
              type: object
              description: New message
              properties:
                content:
                  type: string
                  description: The content of the message
                  pattern: '^[a-zA-Z]+$'
                  example: "Hi, how are you?"
                  minLength: 1
                  maxLength: 500
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                description: Message identifier
                properties:
                  message_id:
                    type: string
                    description: Unique identifier for the sent message
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 16
                    example: "msg12345"

  /conversations/{conversation_id}/messages/{message_id}:
    parameters:
      - name: conversation_id
        in: path
        required: true
        schema:
          type: string
          description: Unique identifier for the conversation
          pattern: '^[a-zA-Z]+$'
          minLength: 3
          maxLength: 16
      - name: message_id
        in: path
        required: true
        schema:
          type: string
          description: Unique identifier for the message
          pattern: '^[a-zA-Z]+$'
          minLength: 3
          maxLength: 16
    delete:
      tags:
        - messages
      summary: Delete a sent message
      description: Allows a user to delete a sent message
      operationId: deleteMessage
      responses:
        '204':
          description: Message deleted successfully
    post:
      tags:
        - messages
      summary: Forward a message
      operationId: forwardMessage
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
        - name: message_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Message forwarded succesfully.
          content:
            application/json:
              schema:
                type: object
                description: Message identifier
                properties:
                  message_id:
                    type: string
                    description: Unique identifier for the message forwarded
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 16
                    example: "msg12345"
                    
  /conversations/{conversation_id}/messages/{message_id}/reactions:
    post:
      tags:
        - reactions
      summary: Comment a message
      operationId: commentMessage
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
        - name: message_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Message comment
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Comment on the message
              properties:
                reaction:
                  type: string
                  example: "<3"
      responses:
        '201':
          description: Comment added succesfully.
          content:
            application/json:
              schema:
                type: object
                description: Comment
                properties:
                  reaction:
                    type: string
                    example: "<3"

    delete:
      tags:
        - reactions
      summary: Delete a message comment
      operationId: uncommentMessage
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
        - name: message_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Comment deleted succesfully.

  /conversations/groups:
    post:
      tags:
        - groups
      summary: Create a new Group Chat
      operationId: addToGroup
      requestBody:
        description: Group Chat information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-zA-Z]+$'
                  minLength: 3
                  maxLength: 30
                  example: "Friends"
                members:
                  type: array
                  items:
                    type: string
                    pattern: '^[a-zA-Z]+$'
                    minItems: 3
                    maxItems: 30
                    example: "user123"
      responses:
        '201':
          description: Group Chat created succesfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  group_id:
                    type: string
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 30
                    example: "grp98765"

  /conversations/groups/{group_id}:
    post:
      tags:
        - groups
      summary: Change the Group Chat name
      operationId: setGroupName
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z]+$'
            minLength: 3
            maxLength: 30
      requestBody:
        description: New Group Chat name
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_name:
                  type: string
                  description: Group Chat name
                  pattern: '^[a-zA-Z]+$'
                  minLength: 3
                  maxLength: 30
                  example: "NewName"
      responses:
        '200':
          description: Group Chat name updated succesfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_name:
                    type: string
                    pattern: '^[a-zA-Z]+$'
                    minLength: 3
                    maxLength: 30
                    example: "NewName"

  /conversations/groups/{group_id}/leave:
    post:
      tags:
        - groups
      summary: Allow an user to leave a Group Chat
      operationId: leaveGroup
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User left the Group Chat succesfully.

  /conversations/groups/{group_id}/photo:
    post:
      tags:
        - groups
      summary: Update the Group Chat photo
      operationId: setGroupPhoto
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z]+$'
            minLength: 40
            maxLength: 100
      requestBody:
        description: New Group Chat photo
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photo_url:
                  type: string
                  description: Photo URL
                  example: "https://example.com/groupphoto.jpg"
      responses:
        '200':
          description: Group Chat photo updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo_url:
                    type: string
                    description: Group Chat photo URL
                    example: "https://example.com/groupphoto.jpg"

  /users/{username}/photo:
    post:
      tags:
        - user
      summary: Update users profile picture
      operationId: setMyPhoto
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z]+$'
            minLength: 3
            maxLength: 16
      requestBody:
        description: New profile picture
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photo_url:
                  type: string
                  description: Profile picture photo URL
                  pattern: '^[a-zA-Z]+$'
                  minLength: 40
                  maxLength: 100
                  example: "https://example.com/photo.jpg"
      responses:
        '200':
          description: Users profile picture updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo_url:
                    type: string
                    description: Profile picture photo URL
                    pattern: '^[a-zA-Z]+$'
                    minLength: 40
                    maxLength: 100
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
