openapi: 3.0.3
info:
  title: WASAText API
  description: API for WASAText.
  version: 1.0.0

tags:
  - name: login
    description: Operations related to user authentication
  - name: user
    description: User related operations
  - name: conversations
    description: Operations related to conversations
  - name: messages
    description: Messages functionalities
  - name: reactions
    description: Reactions to messages
  - name: groups
    description: Group chat operations and management

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        Allows a user to log in by providing a username.
        If the username does not exist, it will be created.
      operationId: doLogin
      requestBody:
        description: Details required for user login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The username to log in
                  example: Maria
                  pattern: '^[a-zA-Z]+$'
                  minLength: 3
                  maxLength: 16
              required:
                - name
      responses:
        '201':
          description: User logged in successfully 
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    description: A unique identifier for the logged-in user
                    example: "abcdef012345"

  /users/{username}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
          description: The username of the user
    put:
      tags:
        - user
      summary: Updates the username
      description: Allows the user to update their username
      operationId: setMyUserName
      requestBody:
        description: The new username to update
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_name:
                  type: string
                  description: New username
                  example: "NewName"
                  pattern: '^[a-zA-Z]+$'
                  minLength: 3
                  maxLength: 16
              required:
                - new_name
      responses:
        '200':
          description: Username updated successfully

  /users/{username}/conversations:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
          description: The username of the user
    get:
      tags:
        - conversations
      summary: List of a users conversations
      description: Returns a list of all conversations for a user
      operationId: getMyConversations
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    conversation_id:
                      type: string
                      description: Unique identifier for the conversation
                    last_message:
                      type: string
                      description: Preview of the last message
                    timestamp:
                      type: string
                      format: date-time
                      description: Timestamp of the last message
                    participants:
                      type: array
                      description: List of participants in the conversation
                      items:
                        type: string
                      minItems: 1
                      maxItems: 50

  /conversations/{conversation_id}:
    parameters:
      - name: conversation_id
        in: path
        required: true
        schema:
          type: string
          description: The unique identifier for the conversation
    get:
      tags:
        - conversations
      summary: Details of a specific conversation
      description: Returns all details of a specific conversation
      operationId: getConversation
      responses:
        '200':
          description: Details of the conversation
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    description: List of messages in the conversation
                    items:
                      type: object
                      properties:
                        message_id:
                          type: string
                          description: Unique identifier for the message
                        sender:
                          type: string
                          description: Username of the sender
                        content:
                          type: string
                          description: The message content
                        timestamp:
                          type: string
                          format: date-time
                          description: Timestamp of the message

  /conversations/{conversation_id}/messages:
    post:
      tags:
        - messages
      summary: Send a new message to the conversation
      description: Allows a user to send a new message to a conversation
      operationId: sendMessage
      requestBody:
        description: Message content
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The content of the message
                  example: "Hi, how are you?"
                  minLength: 1
                  maxLength: 500
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                    description: Unique identifier for the sent message
                    example: "msg12345"

  /conversations/{conversation_id}/messages/{message_id}:
    parameters:
      - name: conversation_id
        in: path
        required: true
        schema:
          type: string
          description: Unique identifier for the conversation
      - name: message_id
        in: path
        required: true
        schema:
          type: string
          description: Unique identifier for the message
    delete:
      tags:
        - messages
      summary: Delete a sent message
      description: Allows a user to delete a sent message
      operationId: deleteMessage
      responses:
        '204':
          description: Message deleted successfully

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
